# DO NOT USE THIS ANYMORE, see readme for release details

deployment:
  tasks:
    - export DEPLOYPATH=/home/lloydcul/epk.birdribs.uk/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp index.php $DEPLOYPATH
    # - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH/public
